{% set name = "necromancer" %}
{% set version = "0.6.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: a41cfc815eb8486dcc1a837b2a0b28b992b7ecee4125015e9bc40c2c83b8b13d

build:
  noarch: generic
  number: 0
  script:
    - gem install --norc -l -V --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }} or {{ rb25 }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.txt
  summary: 'Conversion from one object type to another with a bit of black magic.'
  dev_url: https://github.com/piotrmurach/necromancer

extra:
  recipe-maintainers:
    - sodre
    - rluria14
    - oblute
    - benhuff
