{% set name = "necromancer" %}
{% set version = "0.5.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 6d0be995dd3f69e2d03dfc6e426ab891704dd5bbb903a79730baab4352185ef0

build:
  noarch: generic
  number: 0
  script:
    - gem install --norc -l -V --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.txt
  summary: 'Conversion from one object type to another with a bit of black magic.'
  dev_url: https://github.com/piotrmurach/necromancer

extra:
  recipe-maintainers:
    - sodre
    - rluria14
    - oblute
    - benhuff
