travis:
  secure:
    BINSTAR_TOKEN: egakYYWbqIl2JBibiwSr9nezPYDC03us1TTka1K5FEC0xyuwSH2JhaYgOFphN8A3w4HAg5YPp5YJeDUxMb5Y79PTKWAn3ELckOAcMv5y1UOd3LvEVmMf9w3OsOIaNDXfi5BkMxC/ATLSUi+CeXP5bq5kfLQqKoY+2j4gWBAUphNKAL411tOmgx3TSO4MJYqBMEkSVU76hf+dprW+yJZz/tmg4JwXN6SLTVj4wYhtnZp5ioaYLmb3UhGXL/lkZGCnlTCsXJCS2/aWc2/2yprUdtG9n0y0VGdgXl1w34UTCV2U6QGqkqDPLijmogwwIOmT7eFii8jIe0om0D39O7x5x0V82WfhPPY3nRERXf71DVsJ/NW+2l4ypxY1JTQrntMLxQXyMLsK3pmGF6AA6mhz9RADfak61snNpJ054DDRziRQwfexLkF10A2xw4PuPQTG4TA8CdrepcUJrzUVcvj5aHrEqH5TZgCWZKeJO4k0/P8q2xxuXgbtgu9/r37JX2mDO2fZPCmPDa+Kiig1bZ0kAQ+l0AfJs7rZKcqNhwrjXimLt7BVW4Eh3BxKv52t6gUSJJOcQfjazQp1Ky5CMk8X1bxvaFvuJuRf4i+Qf1IGM6cM36DIiNPmeT7I4PRGHDuxuIMV9Q3g+Uc9Bdbk5Wpl34ULCJ9+0SoruS5WYXjAU/s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
